the-gossip-project_/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/:name', to: 'welcome#name'
  get '/contact', to: 'contact#show_contact'
  get '/realisateur', to: 'realisateur#auteur'
  root to: 'team#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

the-gossip-project_/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the-gossip-project_/app/models/equipe.rb
class Equipe < ApplicationRecord
end

the-gossip-project_/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

the-gossip-project_/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show_contact
  end
end

the-gossip-project_/app/controllers/realisateur_controller.rb
class RealisateurController < ApplicationController
  def auteur
  end
end

the-gossip-project_/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
    @p = Equipe.all
  end
end

the-gossip-project_/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def name
    @nom  =  params[:name]
  end
end

the-gossip-project_/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project_/app/helpers/contact_helper.rb
module ContactHelper
end

the-gossip-project_/app/helpers/realisateur_helper.rb
module RealisateurHelper
end

the-gossip-project_/app/helpers/team_helper.rb
module TeamHelper
end

the-gossip-project_/app/helpers/welcome_helper.rb
module WelcomeHelper
end

the-gossip-project_/app/views/contact/show_contact.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>contact us at +261 34 00 000 00</h1>
    <%=link_to "HOME", root_path%>
    <%=link_to "Team", realisateur_path%>

  </body>
</html>

the-gossip-project_/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

the-gossip-project_/app/views/realisateur/auteur.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>les realisateurs</h1>
    <%= link_to "HOME", root_path%>
    <%= link_to "Contact", contact_path%>
  </body>
</html>

the-gossip-project_/app/views/team/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <% @p.each do |i|%>
    <h1><%= i.name%></h1>
    <h1><%=i.content%></h1>
    <%end%>

    <%= link_to "Real", realisateur_path%>
    <%= link_to "Contact", contact_path%>
  </body>
</html>

the-gossip-project_/app/views/welcome/name.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>welcome <%=@nom%></p>
  </body>
</html>